<a href="https://colab.research.google.com/github/YeiferAlex/EJERCICIOS-Soluci-n-Num-rica-de-Sistemas-de-Ecuaciones-Lineales/blob/main/Copia_de_ejercicios_no_lineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ejercicio 1 eliminacion de gauss
-planteamiento 1

In [ ]:
import numpy as np

A=np.array([[2,3,1],
           [4,1,2],
           [3,4,2]], dtype=float)

b=np.array([0.5,-1.0,1.5], dtype=float)
sol=np.linalg.solve(A,b)

print("solucion del sistema: ")
print(f"x={sol[0]:.4f},y= {sol[1]:.4f},z={sol[2]:.4f}")

solucion del sistema: 
x=-1.3000,y= 0.4000,z=1.9000


planteamiento 2

In [ ]:
import numpy as np

A=np.array([[3,-0.1,-0.2],
           [0.1,0.7,-0.3],
           [0.3,-0.2,10]], dtype=float)

b=np.array([7.85,-19.3,71.4], dtype=float)
sol=np.linalg.solve(A,b)

print("solucion del sistema: ")
print(f"x={sol[0]:.4f},y= {sol[1]:.4f},z={sol[2]:.4f}")

solucion del sistema: 
x=2.2191,y= -25.0719,z=6.5720


ejercicio 2 matriz inversa

In [ ]:
# Matriz de coeficientes
A = np.array([[3,-0.1,-0.2],
              [0.1,0.7,-0.3],
              [0.3,-0.2,10]], dtype=float)

# Vector de salida deseada
b = np.array([7.85,-19.3,71.4], dtype=float)

# Calcular la matriz inversa
A_inv = np.linalg.inv(A)

# Multiplicar A_inv por el vector b
sol = np.dot(A_inv, b)

# Mostrar la solución
print("Pesos ajustados:")
print(f"w1 = {sol[0]:.4f}, w2 = {sol[1]:.4f}, w3 = {sol[2]:.4f}")


Pesos ajustados:
w1 = 2.2191, w2 = -25.0719, w3 = 6.5720


ejercicio 3 metodo de jacobi

In [ ]:
def jacobi(A, b, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0
    for k in range(max_iter):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if i != j)
            x_new[i] = (b[i] - s) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new
        x = x_new
    return x

# Matriz de coeficientes
A = np.array([[10, -1, 2],
              [-1, 11, -1],
              [2, -1, 10]], dtype=float)

# Vector de errores
b = np.array([0.6, 1.5, 2.1], dtype=float)

# Aproximación inicial
x0 = np.zeros_like(b)

# Aplicar el método de Jacobi
sol = jacobi(A, b, x0)
print("Pesos ajustados usando Jacobi:")
print(sol)


Pesos ajustados usando Jacobi:
[0.03201923 0.15923077 0.21951923]


Ejercicio 4: Método Iterativo de Gauss-Seidel

In [ ]:
import numpy as np

def gauss_seidel(A, b, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0
    for k in range(max_iter):
        x_new = np.copy(x)
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i+1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iter

# Matriz de coeficientes
A = np.array([[10, -1, 2 ],
              [-1, 11, -1],
              [2, -1, 10]
              ], dtype=float)

# Vector de términos independientes
b = np.array([5,6,7], dtype=float)

# Valor inicial de las incógnitas
x0 = np.zeros_like(b)

# Resolver el sistema usando el método de Gauss-Seidel
sol, iteraciones = gauss_seidel(A, b, x0)

# Mostrar la solución y el número de iteraciones
print("Solución del sistema:")
print(sol)
print(f"Número de iteraciones: {iteraciones}")


Solución del sistema:
[0.42884615 0.64615385 0.67884615]
Número de iteraciones: 8


ejercicio 5 descomposicion cholesky

In [ ]:
from scipy.linalg import cholesky

# Matriz y vector
A = np.array([[25,15,-5],
              [15,18,0],
              [-5,0,11]], dtype=float)

b = np.array([350,400,200], dtype=float)
# Descomposición de Cholesky
L = cholesky(A, lower=True)

# Resolver Ly = b
y = np.linalg.solve(L, b)

# Resolver L^T x = y
x = np.linalg.solve(L.T, y)

print("Pesos ajustados usando Cholesky:")
print(x)


Pesos ajustados usando Cholesky:
[10.51851852 13.45679012 22.96296296]
